// src/data/testimonials.ts
// Tagged testimonial database for contextual display on quiz results
// Generated: February 9, 2026 | 32 testimonials across 6 retreats

export type GuestType = 'solo' | 'couple' | 'friends' | 'returner';
export type TestimonialFormat = 'video' | 'written';
export type ThemeTag = 'solo' | 'community' | 'adventure' | 'fitness' | 'food' | 'culture' | 'coaching' | 'surprise' | 'growth' | 'relaxation';
export type VibeTag = 'adventure' | 'culture' | 'party' | 'fitness' | 'relaxation' | 'foodie' | 'social';
export type ObjectionTag = 'solo_travel' | 'fitness_level' | 'worth_money' | 'safety' | 'awkward' | null;

export interface Testimonial {
  id: number;
  guestName: string;
  retreatSlug: string;
  retreatDisplay: string;
  guestType: GuestType;
  format: TestimonialFormat;
  pullQuote: string;
  altPullQuote?: string;
  themeTags: ThemeTag[];
  vibeMatch: VibeTag[];
  objectionAddressed: ObjectionTag;
  priority: number; // 1-5, 5 = strongest
  videoUrl?: string;
}

export const testimonials: Testimonial[] = [
  // ═══════════════════════════════════════
  // VIDEO TESTIMONIALS
  // ═══════════════════════════════════════
  {
    id: 1,
    guestName: 'Shane',
    retreatSlug: 'el-salvador-2024',
    retreatDisplay: 'El Salvador',
    guestType: 'solo',
    format: 'video',
    pullQuote: 'I was traveling by myself. I felt like part of the group immediately.',
    altPullQuote: 'There is no shame and only encouragement. If you want to get a sweat on, you can. If you\'re not feeling it, you can do that too.',
    themeTags: ['solo', 'community', 'adventure'],
    vibeMatch: ['adventure', 'social'],
    objectionAddressed: 'solo_travel',
    priority: 5,
    videoUrl: 'https://youtube.com/shorts/2-wfCL1dAXM',
  },
  {
    id: 2,
    guestName: 'Connor',
    retreatSlug: 'el-salvador-2024',
    retreatDisplay: 'El Salvador',
    guestType: 'solo',
    format: 'video',
    pullQuote: 'I was a little worried about being out of shape. To my surprise the entire experience was super laid back.',
    altPullQuote: 'Whether you\'re looking to get healthy or stay healthy or just have a great time, Salty has it all and it\'s your choice.',
    themeTags: ['fitness', 'community', 'relaxation'],
    vibeMatch: ['fitness', 'social'],
    objectionAddressed: 'fitness_level',
    priority: 5,
    videoUrl: 'https://youtube.com/shorts/MtuxUwGmBC0',
  },
  {
    id: 3,
    guestName: 'Keara',
    retreatSlug: 'sicily-v1',
    retreatDisplay: 'Sicily',
    guestType: 'friends',
    format: 'video',
    pullQuote: 'I made amazing friendships with 20, 30 new people and every single day ended with a beautiful family-style meal with incredible food and local Italian wine.',
    themeTags: ['community', 'food', 'culture'],
    vibeMatch: ['social', 'foodie', 'culture'],
    objectionAddressed: null,
    priority: 4,
    videoUrl: 'https://youtube.com/shorts/T_2LVHSVIeU',
  },
  {
    id: 4,
    guestName: 'Cindy',
    retreatSlug: 'el-salvador-2024',
    retreatDisplay: 'El Salvador',
    guestType: 'solo',
    format: 'video',
    pullQuote: 'It was really nice leaning in and turning my brain off during this retreat.',
    altPullQuote: 'Everything was meticulously organized with zero pressure to commit or attend anything.',
    themeTags: ['solo', 'relaxation', 'community'],
    vibeMatch: ['social', 'relaxation'],
    objectionAddressed: 'solo_travel',
    priority: 4,
    videoUrl: 'https://youtube.com/shorts/2-wfCL1dAXM',
  },

  // ═══════════════════════════════════════
  // NICARAGUA 2025
  // ═══════════════════════════════════════
  {
    id: 5,
    guestName: 'Vahik M.',
    retreatSlug: 'nicaragua-2025',
    retreatDisplay: 'Nicaragua',
    guestType: 'solo',
    format: 'written',
    pullQuote: 'Wake up, say hello to sun, bond with friends, workout like hell, sweat, learn new things, laugh, party, and enjoy life. Everything optional except having fun.',
    themeTags: ['fitness', 'community', 'adventure'],
    vibeMatch: ['party', 'fitness', 'social'],
    objectionAddressed: null,
    priority: 4,
  },
  {
    id: 6,
    guestName: 'Naomi T.',
    retreatSlug: 'nicaragua-2025',
    retreatDisplay: 'Nicaragua',
    guestType: 'friends',
    format: 'written',
    pullQuote: 'I went back and forth before booking and wasn\'t sure if this was for me, but I\'m so glad I went for it.',
    altPullQuote: 'There truly was something for everyone. Whether you\'re into workouts, relaxation, social time, or exploring, there was space to enjoy everything at your own pace.',
    themeTags: ['surprise', 'community', 'relaxation'],
    vibeMatch: ['social', 'relaxation', 'adventure'],
    objectionAddressed: 'awkward',
    priority: 5,
  },
  {
    id: 7,
    guestName: 'Chelsea D.',
    retreatSlug: 'nicaragua-2025',
    retreatDisplay: 'Nicaragua',
    guestType: 'friends',
    format: 'written',
    pullQuote: 'A perfect balance of workouts, fun activities, and time to relax and recharge.',
    themeTags: ['relaxation', 'fitness', 'community'],
    vibeMatch: ['fitness', 'relaxation'],
    objectionAddressed: null,
    priority: 3,
  },
  {
    id: 8,
    guestName: 'Aaron S.',
    retreatSlug: 'nicaragua-2025',
    retreatDisplay: 'Nicaragua',
    guestType: 'solo',
    format: 'written',
    pullQuote: 'A great option if you want to deepen your practice in a location that feels a world away from the daily grind and meet awesome new people.',
    altPullQuote: 'The schedule was well-paced with several classes a day and ample time to explore or just read by the pool.',
    themeTags: ['relaxation', 'fitness', 'community'],
    vibeMatch: ['relaxation', 'fitness', 'social'],
    objectionAddressed: null,
    priority: 3,
  },
  {
    id: 9,
    guestName: 'Rhonda C.',
    retreatSlug: 'nicaragua-2025',
    retreatDisplay: 'Nicaragua',
    guestType: 'solo',
    format: 'written',
    pullQuote: 'I went in worried about fitting in, but those worries vanished almost instantly.',
    altPullQuote: 'The workouts were challenging but adaptable, and I never once felt out of place, even trying things that were new to me.',
    themeTags: ['solo', 'fitness', 'coaching', 'surprise'],
    vibeMatch: ['fitness', 'social'],
    objectionAddressed: 'awkward',
    priority: 5,
  },
  {
    id: 10,
    guestName: 'Ashley O.',
    retreatSlug: 'nicaragua-2025',
    retreatDisplay: 'Nicaragua',
    guestType: 'couple',
    format: 'written',
    pullQuote: 'You could go solo or with a friend and you are going to make the best memories. Nothing is forced, and everything is a good time.',
    themeTags: ['community', 'adventure'],
    vibeMatch: ['party', 'social'],
    objectionAddressed: 'solo_travel',
    priority: 4,
  },

  // ═══════════════════════════════════════
  // SICILY V1
  // ═══════════════════════════════════════
  {
    id: 11,
    guestName: 'Sarah F.',
    retreatSlug: 'sicily-v1',
    retreatDisplay: 'Sicily',
    guestType: 'friends',
    format: 'written',
    pullQuote: 'I left with unforgettable memories, new friendships, and a renewed sense of clarity and joy.',
    altPullQuote: 'Nate and Erin are absolutely amazing hosts; their energy, care, and passion made the retreat feel both seamless and special.',
    themeTags: ['coaching', 'community', 'growth'],
    vibeMatch: ['social', 'culture'],
    objectionAddressed: null,
    priority: 4,
  },
  {
    id: 12,
    guestName: 'Justin Y.',
    retreatSlug: 'sicily-v1',
    retreatDisplay: 'Sicily',
    guestType: 'solo',
    format: 'written',
    pullQuote: 'The yoga classes were challenging in the best way possible. Each session pushed me out of my comfort zone and left me feeling stronger and more grounded.',
    altPullQuote: 'Two separate excursions giving us a real taste of the area, and the food was out of this world. And then the dancing... LOTS of it!',
    themeTags: ['fitness', 'culture', 'food', 'community'],
    vibeMatch: ['fitness', 'culture', 'foodie', 'party'],
    objectionAddressed: null,
    priority: 4,
  },
  {
    id: 13,
    guestName: 'Sophie F.',
    retreatSlug: 'sicily-v1',
    retreatDisplay: 'Sicily',
    guestType: 'solo',
    format: 'written',
    pullQuote: 'From the moment I arrived, I was filled with joy, excitement, and a sense of adventure.',
    themeTags: ['community', 'adventure'],
    vibeMatch: ['adventure', 'social'],
    objectionAddressed: null,
    priority: 3,
  },
  {
    id: 14,
    guestName: 'Melissa T.',
    retreatSlug: 'sicily-v1',
    retreatDisplay: 'Sicily',
    guestType: 'solo',
    format: 'written',
    pullQuote: 'It\'s an investment in yourself that\'s worth every moment.',
    altPullQuote: 'There was such a strong sense of community and openness. By the end, it felt like we were all part of something much bigger.',
    themeTags: ['growth', 'community', 'coaching'],
    vibeMatch: ['social', 'relaxation'],
    objectionAddressed: 'worth_money',
    priority: 5,
  },
  {
    id: 15,
    guestName: 'Melissa M.',
    retreatSlug: 'sicily-v1',
    retreatDisplay: 'Sicily',
    guestType: 'friends',
    format: 'written',
    pullQuote: 'Stunning beachfront property, dreamy yoga shala with killer classes, shadowboxing on the beach. Exploring stunning seaside villages like Marzamemi and Taormina.',
    themeTags: ['fitness', 'culture', 'adventure'],
    vibeMatch: ['fitness', 'culture', 'adventure'],
    objectionAddressed: null,
    priority: 3,
  },
  {
    id: 16,
    guestName: 'Olivia A.',
    retreatSlug: 'sicily-v1',
    retreatDisplay: 'Sicily',
    guestType: 'friends',
    format: 'written',
    pullQuote: 'Salty handles all the details of planning a trip, letting you truly relax and have a fun-filled, stress-free vacation.',
    themeTags: ['relaxation', 'community'],
    vibeMatch: ['relaxation', 'social'],
    objectionAddressed: null,
    priority: 3,
  },

  // ═══════════════════════════════════════
  // MOROCCO V1
  // ═══════════════════════════════════════
  {
    id: 17,
    guestName: 'Christyna B.',
    retreatSlug: 'morocco-v1',
    retreatDisplay: 'Morocco',
    guestType: 'friends',
    format: 'written',
    pullQuote: 'I laughed, I cried tears of joy, and I shared moments with some truly incredible souls.',
    themeTags: ['community', 'growth', 'adventure'],
    vibeMatch: ['social', 'adventure'],
    objectionAddressed: null,
    priority: 4,
  },
  {
    id: 18,
    guestName: 'Elena F.',
    retreatSlug: 'morocco-v1',
    retreatDisplay: 'Morocco',
    guestType: 'solo',
    format: 'written',
    pullQuote: 'A perfect mix of travel activities, training, and party. I met some incredible people along the way.',
    themeTags: ['adventure', 'fitness', 'community'],
    vibeMatch: ['adventure', 'party', 'fitness'],
    objectionAddressed: null,
    priority: 3,
  },
  {
    id: 19,
    guestName: 'Jessica K.',
    retreatSlug: 'morocco-v1',
    retreatDisplay: 'Morocco',
    guestType: 'friends',
    format: 'written',
    pullQuote: 'Erin and Nate certainly know how to balance fun, well-being and fitness while discovering the country safely but fully.',
    altPullQuote: 'Along with their top coaches, we never felt out of place or bored.',
    themeTags: ['coaching', 'fitness', 'culture'],
    vibeMatch: ['fitness', 'culture', 'adventure'],
    objectionAddressed: null,
    priority: 4,
  },
  {
    id: 20,
    guestName: 'Laurence B.',
    retreatSlug: 'morocco-v1',
    retreatDisplay: 'Morocco',
    guestType: 'solo',
    format: 'written',
    pullQuote: 'I decided to book last minute and it did not disappoint. To anyone who wants to have fun and be adventurous in a safe and comforting space, this is the retreat for you.',
    altPullQuote: 'From the adventures, to the activities, to the rooftop yoga sessions and beachside parties, this trip will stay in my mind forever.',
    themeTags: ['solo', 'adventure', 'community'],
    vibeMatch: ['adventure', 'social', 'party'],
    objectionAddressed: 'awkward',
    priority: 4,
  },
  {
    id: 21,
    guestName: 'Julie M.',
    retreatSlug: 'morocco-v1',
    retreatDisplay: 'Morocco',
    guestType: 'solo',
    format: 'written',
    pullQuote: 'From surfing and workouts to yoga and exploring this beautiful country, every day was filled with unforgettable experiences.',
    altPullQuote: 'The space they created allowed for deep connection, fun, and personal growth.',
    themeTags: ['adventure', 'fitness', 'growth'],
    vibeMatch: ['adventure', 'fitness', 'culture'],
    objectionAddressed: null,
    priority: 3,
  },
  {
    id: 22,
    guestName: 'Catherine T.',
    retreatSlug: 'morocco-v1',
    retreatDisplay: 'Morocco',
    guestType: 'friends',
    format: 'written',
    pullQuote: 'To arrive somewhere you\'ve never been with people you\'ve never met, and leave with a whole new group of friends, is just so special.',
    altPullQuote: 'I truly think they offer something for everyone: younger adults, retirees, couples, solo-travelers, friend groups.',
    themeTags: ['solo', 'community', 'surprise'],
    vibeMatch: ['social', 'adventure'],
    objectionAddressed: 'solo_travel',
    priority: 5,
  },
  {
    id: 23,
    guestName: 'Beth C.',
    retreatSlug: 'morocco-v1',
    retreatDisplay: 'Morocco',
    guestType: 'friends',
    format: 'written',
    pullQuote: 'From the markets in Marrakech to the surfing, the cliff jumping at Paradise Valley, and the sand dune surfing. All with friendly people both locally and on the retreat.',
    themeTags: ['adventure', 'culture', 'food'],
    vibeMatch: ['adventure', 'culture', 'foodie'],
    objectionAddressed: null,
    priority: 4,
  },
  {
    id: 24,
    guestName: 'Danielle H.',
    retreatSlug: 'morocco-v1',
    retreatDisplay: 'Morocco',
    guestType: 'couple',
    format: 'written',
    pullQuote: 'You can be a beginner or pro in the fitness field and no matter what, you\'ll still be welcomed with open arms.',
    altPullQuote: 'Every retreat itinerary is optional so if you\'re not feeling up to something, there is a zero judgement zone.',
    themeTags: ['fitness', 'community', 'relaxation'],
    vibeMatch: ['fitness', 'social', 'relaxation'],
    objectionAddressed: 'fitness_level',
    priority: 5,
  },
  {
    id: 25,
    guestName: 'Jude C.',
    retreatSlug: 'morocco-v1',
    retreatDisplay: 'Morocco',
    guestType: 'solo',
    format: 'written',
    pullQuote: 'Everyone I know should experience at least one of their retreats. Erin and Nate plan everything for everyone perfectly.',
    themeTags: ['coaching', 'community'],
    vibeMatch: ['social'],
    objectionAddressed: null,
    priority: 3,
  },
  {
    id: 26,
    guestName: 'V L.',
    retreatSlug: 'morocco-v1',
    retreatDisplay: 'Morocco',
    guestType: 'friends',
    format: 'written',
    pullQuote: 'I came for the adventure and left with soul connections, epic memories, and activities I never imagined doing.',
    themeTags: ['adventure', 'community', 'surprise'],
    vibeMatch: ['adventure', 'social'],
    objectionAddressed: null,
    priority: 3,
  },

  // ═══════════════════════════════════════
  // COSTA RICA V2
  // ═══════════════════════════════════════
  {
    id: 27,
    guestName: 'Brooks H.',
    retreatSlug: 'costa-rica-v2',
    retreatDisplay: 'Costa Rica',
    guestType: 'friends',
    format: 'written',
    pullQuote: 'Salty knows how to balance out everything beautifully: exercise, adventure, relaxation, and serenity. The group was a fantastic mix of positive, interesting people.',
    altPullQuote: 'A trip that\'s fully organized for you, while getting active, learning new workouts and a new culture, eating delicious healthy meals, all with a ton of flexibility.',
    themeTags: ['fitness', 'community', 'adventure', 'food'],
    vibeMatch: ['fitness', 'adventure', 'social', 'foodie'],
    objectionAddressed: null,
    priority: 4,
  },
  {
    id: 28,
    guestName: 'Sarah G.',
    retreatSlug: 'costa-rica-v2',
    retreatDisplay: 'Costa Rica',
    guestType: 'couple',
    format: 'written',
    pullQuote: 'Options for surf, yoga, Pilates and strength workouts, or if you just want to hang out and soak up the sun, that\'s more than welcome.',
    themeTags: ['fitness', 'relaxation', 'adventure'],
    vibeMatch: ['fitness', 'relaxation', 'adventure'],
    objectionAddressed: 'fitness_level',
    priority: 3,
  },

  // ═══════════════════════════════════════
  // MEXICO 2024
  // ═══════════════════════════════════════
  {
    id: 29,
    guestName: 'Julianne M.',
    retreatSlug: 'mexico-2024',
    retreatDisplay: 'Mexico',
    guestType: 'returner',
    format: 'written',
    pullQuote: 'The price felt high at first, but the price and consequences of neglecting yourself are even higher. It altered the course of my life.',
    altPullQuote: 'Everyone had an almost inexplicable desire to support one another and foster connection. Whether with a laugh, an embrace, a celebration, a margarita or a listening ear.',
    themeTags: ['growth', 'community', 'fitness', 'coaching'],
    vibeMatch: ['social', 'fitness', 'relaxation'],
    objectionAddressed: 'worth_money',
    priority: 5,
  },
  {
    id: 30,
    guestName: 'Aldona M.',
    retreatSlug: 'mexico-2024',
    retreatDisplay: 'Mexico',
    guestType: 'friends',
    format: 'written',
    pullQuote: 'I was in dire need of a major reboot. Mentally, socially and physically. At SALTY, I got it all and more.',
    altPullQuote: 'I had the opportunity to connect with a beautiful group of people who I can\'t help but call family now. A week of ultimate bliss and pure happiness.',
    themeTags: ['growth', 'community', 'coaching'],
    vibeMatch: ['social', 'fitness', 'relaxation'],
    objectionAddressed: null,
    priority: 5,
  },
  {
    id: 31,
    guestName: 'Hussein E.',
    retreatSlug: 'mexico-2024',
    retreatDisplay: 'Mexico',
    guestType: 'friends',
    format: 'written',
    pullQuote: 'Erin and Nate created a space where strangers became family, and we left with a bond so rare and special.',
    altPullQuote: 'A week filled with boundless laughter, unforgettable moments, movement, breathing, dancing, surfing, stargazing, self-discovery, and above all, love and connection.',
    themeTags: ['community', 'adventure', 'coaching'],
    vibeMatch: ['social', 'adventure', 'party'],
    objectionAddressed: null,
    priority: 4,
  },

  // ═══════════════════════════════════════
  // MULTI-RETREAT RETURNER
  // ═══════════════════════════════════════
  {
    id: 32,
    guestName: 'Mandala M.',
    retreatSlug: 'sicily-v1', // primary slug for matching, but covers multiple
    retreatDisplay: 'Sicily + El Salvador',
    guestType: 'returner',
    format: 'written',
    pullQuote: 'A great way to travel alone or with friends. All details are taken care of. SALTY has given me the opportunity to challenge myself, reflect and grow in ways I was not expecting.',
    altPullQuote: 'I have made so many likeminded friends on each trip. Already looking forward to my next getaway with SALTY.',
    themeTags: ['growth', 'solo', 'community', 'adventure'],
    vibeMatch: ['adventure', 'social', 'fitness'],
    objectionAddressed: 'solo_travel',
    priority: 5,
  },
];

// ═══════════════════════════════════════
// RETREAT SLUG CROSS-REFERENCE
// ═══════════════════════════════════════
// For retreats without their own testimonials,
// pull from related retreats in the same region.
export const retreatTestimonialFallbacks: Record<string, string[]> = {
  // Current/upcoming retreats → fallback sources
  'costa-rica-v3': ['costa-rica-v2'],
  'costa-rica-v4': ['costa-rica-v2', 'costa-rica-v3'],
  'sri-lanka': ['morocco-v1', 'sicily-v1'],        // no direct testimonials yet
  'panama': ['el-salvador-2024', 'nicaragua-2025'], // Central America pool
  'morocco-v2': ['morocco-v1'],
  'sicily-v2': ['sicily-v1'],
  'el-salvador-2026': ['el-salvador-2024'],
};
